apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tutum-hello-world-dep
  name: tutum-hello-world-dep
  namespace: tutum
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tutum-hello-world-pods
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tutum-hello-world-pods
    spec:
      containers:
      - image: tutum/hello-world
        imagePullPolicy: Always
        name: tutum-hello-world
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tutum-hello-world-svc
  namespace: tutum
spec:
  ports:
  - nodePort: 32366
    port: 9000
    protocol: TCP
    targetPort: 80
  selector:
    app: tutum-hello-world-pods
  type: LoadBalancer